[tool.poetry]
name = "raingen"
version = "0.0.1"
description = "Fan-edit of the warrior cat clangen game"
license = "MPL-2.0"
authors = [
    "Sablesteel <noemail@null.com>"
]
readme = "README.md"
repository = "https://github.com/sunflower8804/raingen-latest/"
keywords = ["warriorcats", "fanedit", "game", "pygame"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
pygame-ce = "^2.2.1"
ujson = "^5.7.0"
pygame-gui = "0.6.12"
platformdirs = "^3.3.0"
pypresence = { version = "^4.2.1", optional = true }
pgpy = "^0.6.0"
requests = "^2.28.2"
strenum = "^0.4.10"
black = { version = "^23.0", python = ">=3.8," }
cryptography = "^42.0.0"

[tool.poetry.group.test]
optional = true
[tool.poetry.group.test.dependencies]
pylint = "^2.17.3"
jsonschema = "^4.23.0"

[tool.poetry.group.build]
optional = true
[tool.poetry.group.build.dependencies]
pyinstaller = "^6.6.0"
pillow = "^9.5.0"
setuptools = "^67.7.2"
wheel = "^0.40.0"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
mkdocs-material = ">=9.5.49"
mkdocs = ">=1.6.1"
mkdocs-git-committers-plugin-2 = ">=2.4.1"
mkdocs-git-revision-date-localized-plugin = ">=1.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"

[tool.poetry.extras]
discord = ["pypresence"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]